# docs: https://help.github.com/en/articles/workflow-syntax-for-github-actions

name: Unit Test

on: push

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Dependencies
      run: npm install

    - name: Unit Testing
      run: npm run test